<html>
	<head>
		<title>New Contact</title>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
	</head>
	<body>
		<p><a class="pure-button pure-button-primary" href="/">Back To List</a></p>
		<form class="pure-form pure-form-stacked" method="POST" enctype="multipart/form-data">
			<fieldset>
				<legend>Add New User</legend>

				<div class="pure-g">
					<div class="pure-u-1 pure-u-md-1-3">
						<label for="full_name">Full Name</label>
						<input id="full_name" name="full_name" class="pure-u-1" type="text" required>
					</div>

					<div class="pure-u-1 pure-u-md-1-3">
						<label for="phone">Phone Number</label>
						<input id="phone_number" name="phone_number" pattern="0\d{8}" placeholder="Format 0XXXXXXXX" class="pure-u-1" type="tel" required>
					</div>

					<div class="pure-u-1 pure-u-md-1-3">
						<label for="birthday">Bitrhday</label>
						<input id="birthday" name="birthday" class="pure-u-1" type="date">
					</div>
					
					<div class="pure-u-1 pure-u-md-1-3">
						<label for="address">Address</label>
						<input id="address" name="address" class="pure-u-1" type="text">
					</div>
					
					<div class="pure-u-1 pure-u-md-1-3">
						<label for="avatar">Avatar</label>
						<input id="avatar" name="avatar" class="pure-u-1" type="file">
					</div>
					
				</div>
				
				<button type="submit" class="pure-button pure-button-primary">Add</button>
			</fieldset>
		</form>
	</body>
</html>