<html>
	<head>
		<title>Phonebook</title>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
		<style>
			.action-form
			{
				margin: 0px;
			}
		</style>
	</head>
	<body>
		<h1>Phonebook</h1>
		<p><a class="pure-button pure-button-primary" href="/users/new">Add new user</a></p>
		<?php if(isset($messages["success"])): ?>
			<p class="success"><?php echo $messages["success"][0]; ?></p>
		<?php elseif(isset($messages["error"])): ?>
			<p class="error"><?php echo $messages["error"][0]; ?></p>
		<?php endif; ?>
		<form class="pure-form">
			<fieldset>
				<input value="<?php echo $q ?>" type="text" placeholder="keyword" name="q">
				<button type="submit" class="pure-button pure-button-primary">Search</button>
			</fieldset>
		</form>
		<?php if($users && is_array($users)): ?>
		<table class="pure-table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Avatar</th>
					<th>Full Name</th>
					<th>Phone Number</th>
					<th>Birthday</th>
					<th>Adddress</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1; foreach($users as $user): ?>
				<tr <?php if($i % 2 == 0): ?>  class="pure-table-odd" <?php endif; ?> >
					<td><?php echo $user->getId(); ?></td>
					<td><?php if(file_exists("images/".$user->getId())): ?><img width="50" src="images/<?php echo $user->getId(); ?>" /><?php endif; ?></td>
					<td><?php echo $user->getFullName(); ?></td>
					<td><?php echo $user->getPhoneNumber(); ?></td>
					<td><?php echo $user->getBirthday(); ?></td>
					<td><?php echo $user->getAddress(); ?></td>
					<td>
						<form class="action-form" action="/users/<?php echo $user->getId(); ?>" method="post">
							<a class="pure-button" href="/users/<?php echo $user->getId(); ?>">Edit</a>
							<input type="hidden" name="_METHOD" value="DELETE"/>
							<input class="pure-button" type="submit" value="Delete"/>
						</form>
					</td>
				</tr>
				<?php $i++; endforeach; ?>
			</tbody>
		</table>
		<?php else: ?>
			<h1>No Records</h1>
		<?php endif; ?>
	</body>
</html>