<html>
	<head>
		<title>Edit Contact</title>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
	</head>
	<body>
		<p><a class="pure-button pure-button-primary" href="/">Back To List</a></p>
		<?php if(isset($messages["success"])): ?>
			<p class="success"><?php echo $messages["success"][0]; ?></p>
		<?php elseif(isset($messages["error"])): ?>
			<p class="error"><?php echo $messages["error"][0]; ?></p>
		<?php endif; ?>
		<form class="pure-form pure-form-stacked" method="POST" enctype="multipart/form-data">
			<fieldset>
				<legend>Edit User</legend>

				<div class="pure-g">
					<div class="pure-u-1 pure-u-md-1-3">
						<label for="full_name">Full Name</label>
						<input id="full_name" name="full_name" value="<?php echo $user->getFullName(); ?>" class="pure-u-1" type="text" required>
					</div>

					<div class="pure-u-1 pure-u-md-1-3">
						<label for="phone">Phone Number</label>
						<input id="phone_number" name="phone_number" pattern="0\d{8}" value="<?php echo $user->getPhoneNumber(); ?>" class="pure-u-1" type="tel" required>
					</div>

					<div class="pure-u-1 pure-u-md-1-3">
						<label for="birthday">Bitrhday</label>
						<input id="birthday" name="birthday" value="<?php echo $user->getBirthday(); ?>" class="pure-u-1" type="date">
					</div>
					
					<div class="pure-u-1 pure-u-md-1-3">
						<label for="address">Address</label>
						<input id="address" name="address" value="<?php echo $user->getAddress(); ?>" class="pure-u-1" type="text">
					</div>
					
					<div class="pure-u-1 pure-u-md-1-3">
						<?php if(file_exists("images/".$user->getId())): ?><img width="50" src="/images/<?php echo $user->getId(); ?>" /><?php endif; ?>
						<label for="avatar">Avatar</label>
						<input id="avatar" name="avatar" class="pure-u-1" type="file">
					</div>
					
				</div>
				<input type="hidden" name="_METHOD" value="PUT"/>
				<button type="submit" class="pure-button pure-button-primary">Save</button>
			</fieldset>
		</form>
	</body>
</html>